* Outline

Goal here this AM is to get things listed out for the road to reality
newsletter. I know that I have done this before in various capacities, so
today's goal is to get at least 1000 words of outline done, and then to start
listing out the essays that will be required. Remember, no need to be too
precious about the whole thing.

I am using this new keyboard too, also a bit of a trip.

* Project Requirements

The essays will be written in, ideally, org mode if I can figure out how to get
that working.

Scratch that. I want to have an example that lives in org-mode but have most of
the thing actually be in markdown, so that other people can copy it and so that
we have as little indirection as possible.

- notebook template, so users can follow along.
- Each essay should be in its own markdown file.
- TOOLS guide inside of the project, describing how the project itself is built.
  That can be another essay at first, so still lives in CLerk land.

Suggested workflow for how the user can do their own thing.
